github: https://github.com/jayfischer
author: Conor Fischer
author_image: https://via.placeholder.com/150
bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
url: "https://conorfischer.com"
baseurl: ""


google_analytics: UA-XXXXX-Y

footer:
  date_format: "%Y"
  author: Conor Fischer
  url: https://github.com/jayfischer
  statement_of_rights: All rights reserverd.


paginate: 10
per_page: 10
paginate_path: '/page/:num/'

urls:
    - text: Blog
      url: /
    - text: About Me
      url: /about/
    - text: Contact
      url: /contact/

markdown: kramdown

sass:
    style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []
