author: Conor Fischer
author_image: https://via.placeholder.com/150
bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
url: "https://conorfischer.com"
baseurl: ""
permalink: /:year/:month/:day/:title:output_ext

google_analytics: UA-XXXXX-Y

footer:
  date_format: "%Y"
  author: Conor Fischer
  url: https://github.com/jayfischer
  statement_of_rights: All rights reserverd.

navigation:
    - text: Blog
      url: /
    - text: Categories
      url: /categories/
    - text: About Me
      url: /about/
    - text: Contact
      url: /contact/

social:
  github:
    name: jayfischer
    url: https://github.com/jayfischer
  twitter:
    name: conor_fischer
    url: https://twitter.com/conor_fischer

# Project Configs

paginate: 10
per_page: 10
paginate_path: '/page/:num/'

markdown: kramdown

highlighter: rouge

sass:
    style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []
